server:
  port: 8080
  servlet:
    context-path: /
management:
  server:
    servlet:
      context-path: /management
    port: 8081
  endpoint:
    conditions.enabled: false
    beans.enabled: false
    configprops.enabled: false
    threaddump.enabled: true
    env.enabled: false
    health.enabled: true
    info.enabled: false
    mappings.enabled: false
    metrics.enabled: true
    shutdown.enabled: false
    httptrace.enabled: false
spring:
  application.name: football-team-service
  pid.file: ${java.io.tmpdir}/football-team-service-api.pid
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      pool-name: football-team-service-dbconnectionpool
  jpa:
    show-sql: false
    database: postgresql
    hibernate:
      ddl-auto: validate
---

spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5430/football_team
    username: postgres
    password: football_team
---

spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test_db
  flyway:
    enabled: false
  jpa:
    show-sql: false
    database: h2
    hibernate:
      ddl-auto: create

