version: '3.1'

services:
  football-team-postgres:
    image: postgres
    restart: always
    ports:
      - 5430:5432
    environment:
      - POSTGRES_DB=football_team
      - POSRGRES_USER=postgres
      - POSTGRES_PASSWORD=football_team